### ISSUE TITLE
Mise à jour de l'année dans le fichier de licence

### ISSUE THREAD

**Issue by bzg** [Codes-sources-de-la-Justice/TRISTAN#49]
Hello, le [fichier de licence](https://github.com/Codes-sources-de-la-Justice/TRISTAN/blob/master/LICENSE) devrait indiquer 2021-2022 pour l'année.  Bonne journée !

**Comment by RaitoBezarius** [comment]
Merci @bzg pour ton retour rapide ! Excellente journée à toi !
